// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: js7xbhyMDXu3U4xUyjvjor
// Component: foL6cdpVnQ
import * as React from "react";
import Head from "next/head";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import Header from "../../Header"; // plasmic-import: -Ea7nJbv4LT/component
import Footer from "../../Footer"; // plasmic-import: X4oZepRJzT2/component
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_roxborough_greens.module.css"; // plasmic-import: js7xbhyMDXu3U4xUyjvjor/projectcss
import sty from "./PlasmicInformation.module.css"; // plasmic-import: foL6cdpVnQ/css

export const PlasmicInformation__VariantProps = new Array();

export const PlasmicInformation__ArgProps = new Array();

function PlasmicInformation__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <Header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("__wab_instance", sty.header)}
          />

          <div className={classNames(projectcss.all, sty.freeBox___487C6)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__xFihH
              )}
            >
              {"Information"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__hD8Rf
              )}
            >
              {"All the information you could hope to find."}
            </div>

            <div className={classNames(projectcss.all, sty.freeBox__vrIoZ)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__o24Cx
                )}
              >
                {
                  'Create share standards-compliant ecologies life-hacks applications functionalities embrace, "reinvent efficient utilize podcasts technologies, visualize," killer social sexy beta-test open-source channels platforms scale. Cross-platform e-enable convergence A-list e-enable user-centred data-driven rich-clientAPIs holistic eyeballs schemas B2B world-class methodologies; A-list orchestrate ROI. Metrics, "value-added, networkeffects eyeballs unleash scale, deploy leverage," platforms enable communities visualize, revolutionary. Enable channels turn-key extensible interactive world-class visualize visualize revolutionary, interfaces rss-capable; orchestrate blogospheres. Mission-critical reinvent integrate, e-commerce value-added killer incentivize robust deploy frictionless, "niches enable," turn-key enterprise A-list expedite experiences bricks-and-clicks embedded reintermediate share. Synergize deliverables e-business sexy Cluetrain syndicate innovate. Technologies weblogs embrace monetize share share, beta-test cross-media strategize peer-to-peer post transform transform.\n\nReal-time bricks-and-clicks web services engage, integrate harness next-generation mission-critical platforms experiences synergize, blogging scale, "channels innovative." Enable global, vertical integrate end-to-end bandwidth folksonomies, mesh frictionless. Portals robust content applications utilize reinvent share schemas. Incentivize wireless viral unleash frictionless platforms paradigms, enable channels viral value; enable scalable enterprise: integrateAJAX-enabled data-driven semantic experiences seize proactive world-class enterprise, engage transform integrateAJAX-enabled. Integrated, share exploit streamline e-commerce reinvent dot-com leverage customized deliverables turn-key B2C, whiteboard applications data-driven optimize vertical infomediaries; interfaces?'
                }
              </div>
            </div>
          </div>

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </p.Stack>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "header", "footer"],
  header: ["header"],
  footer: ["footer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicInformation__ArgProps,
      internalVariantPropNames: PlasmicInformation__VariantProps
    });

    return PlasmicInformation__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicInformation";
  } else {
    func.displayName = `PlasmicInformation.${nodeName}`;
  }
  return func;
}

export const PlasmicInformation = Object.assign(
  // Top-level PlasmicInformation renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicInformation
    internalVariantProps: PlasmicInformation__VariantProps,
    internalArgProps: PlasmicInformation__ArgProps
  }
);

export default PlasmicInformation;
/* prettier-ignore-end */
